stocks = [
'GRTS', 'SPWR', 'VUZI', 'D', 'PBCT', 'CLNE', 'LTRPB', 'CNX', 'HEPA', 'CELH', 'KR', 'NXST', 'AY', 'FFWM', 'MA', 'JPM', 'CYRN', 'IBM', 'WPM', 'BLK', 'SD', 
'CBOE', 'SHC', 'COOP', 'YETI', 'MSGE', 'ELOX', 'MP', 'BOKF', 'PTC', 'LOGC', 'AMRS', 'MRVI', 'NSH', 'AWR', 'SYY', 'DXC', 'RKT', 'AUY', 'VNDA', 'IBOC', 
'FLWS', 'REVG', 'RGP', 'CNET', 'RMNI', 'EGY', 'NEP', 'ZKIN', 'ALL', 'MGNX', 'ITP', 'SLAB', 'CWT', 'GEF', 'PRIM', 'CYTK', 'SXC', 'EOLS', 'LMFA', 'HRI', 
'GL', 'TFC', 'BLI', 'TTWO', 'PRPL', 'ADPT', 'RLGY', 'SSRM', 'IDEX', 'CFG', 'GRMN', 'PAVM', 'PAE', 'AZRE', 'YUM', 'ALGN', 'BDC', 'MDC', 'GBIO', 'PH', 
'RDN', 'CCXI', 'STZ', 'LIVN', 'CNK', 'NDRA', 'DGNS', 'NATI', 'FBNC', 'AVY', 'NH', 'IMMR', 'PIRS', 'SVRA', 'BHAT', 'FISV', 'BCLI', 'SBBP', 'AVNT', 'DVD', 
'DISCK', 'SJI', 'MTZ', 'PAYC', 'XEC', 'AMZN', 'KXIN', 'MYE', 'TLYS', 'VRNT', 'BMRN', 'AVT', 'VST', 'FFIC', 'SCHW', 'GBCI', 'URBN', 'VIAV', 'ATVI', 'ABBV',
 'CLXT', 'PQG', 'MOS', 'EVGN', 'RVMD', 'SEAS', 'GLMD', 'BRC', 'IPAR', 'ANGI', 'CODX', 'EXTR', 'VKTX', 'ATSG', 'NET', 'HEC', 'AROC', 'H', 'AGE', 'GLNG', 
'NEPT', 'AJAX', 'JNPR', 'JIH', 'ABMD', 'LLNW', 'HARP', 'STIM', 'RIDE', 'AME', 'ATRA', 'AGS', 'RNST', 'RADI', 'ALLY', 'TRVN', 'MHO', 'QCOM', 'KMX', 'PLMR', 
'AGFS', 'CTAC', 'CSOD', 'LSEA', 'RDFN', 'TIG', 'NYMX', 'FOUR', 'POOL', 'XBIT', 'MANU', 'JBHT', 'KODK', 'AMD', 'TBLT', 'NVRO', 'CIEN', 'SANM', 'CRHC', 
'GOEV', 'ITT', 'NXTC', 'TFX', 'MG', 'CARS', 'CHS', 'LLY', 'WDC', 'UFS', 'SA', 'FRBK', 'VSAT', 'EMAN', 'BHLB', 'RPAY', 'LULU', 'SBG', 'K', 'VCRA', 'WSBC', 
'BIOX', 'PME', 'CMBM', 'KRO', 'FTS', 'CNR', 'REFR', 'HLI', 'CATM', 'PLTR', 'MAAC', 'UAL', 'ORCC', 'TRUE', 'INSG', 'CI', 'XXII', 'UPS', 'BLUE', 'ADV', 
'TOPS', 'KEY', 'EXPR', 'RMO', 'ACM', 'TWST', 'IMAX', 'BOOT', 'AEO', 'UBX', 'CNCE', 'SKY', 'RESN', 'SSB', 'MCHX', 'ROL', 'UNM', 'HRC', 'SSPK', 'HP', 'RNR',
 'LII', 'GRBK', 'EYPT', 'ADNT', 'DKS', 'ACCD', 'MRC', 'CHNG', 'WH', 'CTXR', 'STCN', 'URG', 'RNG', 'DGNR', 'AVGO', 'ROKU', 'GLG', 'MGTA', 'FOCS', 'SLNO', 
'TCF', 'CHDN', 'HMN', 'GOSS', 'QRVO', 'FIZZ', 'VIAC', 'MLHR', 'ALE', 'FREE', 'HWC', 'FLXN', 'DRVN', 'NAVI', 'OSW', 'C', 'MFIN', 'VEEV', 'SBUX', 'RUN', 'HOLI',
 'EXTN', 'MWA', 'POAI', 'UONE', 'PXD', 'PINS', 'AZPN', 'ID', 'MRNA', 'SPNV', 'BBY', 'CVA', 'GRPN', 'TDC', 'PAYA', 'NGMS', 'ADXS', 
'SU', 'RBAC', 'LAD', 'SPT', 'RCUS', 'OPRT', 'ATR', 'DAL', 'SCPL', 'KIQ', 'HCKT', 'ALTU', 'KEN', 'BKR', 'NDAQ', 'MRCY', 'NR', 'J', 'ESGC', 'PZZA', 
'SWI', 'AFMD', 'GATX', 'STRL', 'MAXN', 'AMSC', 'TLRY', 'NLS', 'XPL', 'AVCO', 'INTU', 'PINC', 'SYRS', 'ZNTL', 'IHRT', 'LPX', 'CCK', 'MNRO', 'BNED', 'BLU', 
'SOAC', 'ASRT', 'BTWN', 'HFWA', 'VC', 'HCSG', 'ARCT', 'VGZ', 'AEM', 'KDP', 'BJ', 'GTN', 'SPR', 'SPLK', 'UMBF', 'CCJ', 'LKFN', 'VFC', 'SYKE', 'TGLS', 
'TR', 'MDU', 'GIL', 'CENTA', 'GE', 'LEA', 'HLF', 'AXSM', 'CMCSA', 'LASR', 'UBS', 'FL', 'CBAT', 'CHGG', 'CRTX', 'SPNE', 'FATE', 'HTBX', 'ATUS', 'TROW', 'DTIL',
 'AN', 'ATEC', 'ALKS', 'KTB', 'ADT', 'IBKR', 'VRCA', 'BMO', 'ADCT', 'ADMP', 'XNCR', 'STFC', 'SNPS', 'CNA', 'PENN', 'WLK', 'TREB', 'WCC', 'KSU', 'TUP', 'TFSL',
 'WERN', 'IOVA', 'GLDG', 'LCI', 'PRI', 'EYEN', 'III', 'MTSI', 'NMRK', 'SALM', 'NWSA', 'BTRS', 'ZEN', 'ALNY', 'CVI', 'XELA', 'SIX', 'PFC', 'REPL', 'VSTM', 
'HII', 'SCCO', 'RGNX', 'DRQ', 'KO', 'SWBI', 'IT', 'LCY', 'GLDD', 'NOVA', 'CO', 'SIBN', 'GNK', 'MATW', 'HZN', 'CRMD', 'SFNC', 'JAGX', 'RJF', 'FURY', 'ALGS',
 'SATS', 'ANSS', 'RRD', 'RICE', 'COTY', 'BIGC', 'ALK', 'IGMS', 'GOCO', 'VCYT', 'SUNW', 'KFY', 'VHC', 'GNUS', 'MOH', 'JCI', 'DSGX', 'SAIA', 'ATHX', 'SF', 
'SRGA', 'IRDM', 'DNN', 'ANET', 'SYBX', 'NGM', 'VOYA', 'TAST', 'DESP', 'KNSA', 'LPRO', 'PPL', 'ODFL', 'THTX', 'AGR', 'CRNT', 'GTE', 'LUNG', 'PRVB', 'NAKD', 
'CLF', 'CSLT', 'COHU', 'SC', 'VYGR', 'SPSC', 'TFII', 'ODT', 'CVS', 'VRSN', 'AMCX', 'SRNE', 'PIPP', 'STBA', 'NSTG', 'PAHC', 'AER', 'MRNS', 'LYFT', 'GTHX', 
'SIC', 'LUV', 'LBRDA', 'AM', 'PFGC', 'MMSI', 'WTRH', 'TRMK', 'CASA', 'PFIE', 'RIOT', 'ASIX', 'PLUG', 'AMRC', 'NEE', 'VERB', 'PLAB', 'STE', 'CKPT', 'BKNG', 
'TRV', 'BALY', 'ALLO', 'FTCV', 'CRNX', 'PRFT', 'ON', 'STN', 'LXFR', 'FOLD', 'MCRB', 'PPD', 'FAII', 'FBC', 'LANC', 'HZAC', 'SNPR', 'TG', 'PTVE', 'EXK', 'PVH', 
'ASGN', 'ORMP', 'ALEC', 'CMP', 'OMI', 'SEER', 'IRBT', 'MDB', 'GASS', 'PNW', 'FLR', 'PLYA', 'OBSV', 'AVRO', 'LRN', 'SCI', 'ADMS', 'ACAD', 'WW', 'NWS', 'EYE',
 'UBSI', 'PACW', 'GLOB', 'NYCB', 'IBIO', 'PODD', 'CAAP', 'PRAA', 'MLM', 'PGEN', 'SPOT', 'XERS', 'ANIX', 'TVTY', 'GSS', 'LOGI', 'EXPO', 'UTI', 'RBBN', 'AAU',
 'KNTE', 'MMI', 'JNCE', 'BBIO', 'HGBL', 'AR', 'RY', 'NNBR', 'AMTI', 'CTAQ', 'OMF', 'XL', 'TNET', 'SHAK', 'CL'
]
