stocks = [
'GRTS', 'SPWR', 'VUZI', 'D', 'PBCT', 'CLNE', 'LTRPB', 'CNX', 'HEPA', 'CELH', 'KR', 'NXST', 'AY', 'FFWM', 'MA', 'JPM', 'CYRN', 'IBM', 'WPM', 'BLK', 'SD', 
'CBOE', 'SHC', 'COOP', 'YETI', 'MSGE', 'ELOX', 'MP', 'BOKF', 'PTC', 'LOGC', 'AMRS', 'MRVI', 'NSH', 'AWR', 'SYY', 'DXC', 'RKT', 'AUY', 'VNDA', 'IBOC', 
'FLWS', 'REVG', 'RGP', 'CNET', 'RMNI', 'EGY', 'NEP', 'ZKIN', 'ALL', 'MGNX', 'ITP', 'SLAB', 'CWT', 'GEF', 'PRIM', 'CYTK', 'SXC', 'EOLS', 'LMFA', 'HRI', 
'GL', 'TFC', 'BLI', 'TTWO', 'PRPL', 'ADPT', 'RLGY', 'SSRM', 'IDEX', 'CFG', 'GRMN', 'PAVM', 'PAE', 'AZRE', 'YUM', 'ALGN', 'BDC', 'MDC', 'GBIO', 'PH', 
'RDN', 'CCXI', 'STZ', 'LIVN', 'CNK', 'NDRA', 'DGNS', 'NATI', 'FBNC', 'AVY', 'NH', 'IMMR', 'PIRS', 'SVRA', 'BHAT', 'FISV', 'BCLI', 'SBBP', 'AVNT', 'DVD', 
'DISCK', 'SJI', 'MTZ', 'PAYC', 'XEC', 'AMZN', 'KXIN', 'MYE', 'TLYS', 'VRNT', 'BMRN', 'AVT', 'VST', 'FFIC', 'SCHW', 'GBCI', 'URBN', 'VIAV', 'ATVI', 'ABBV',
 'CLXT', 'PQG', 'MOS', 'EVGN', 'RVMD', 'SEAS', 'GLMD', 'BRC', 'IPAR', 'ANGI', 'CODX', 'EXTR', 'VKTX', 'ATSG', 'NET', 'HEC', 'AROC', 'H', 'AGE', 'GLNG', 
'NEPT', 'AJAX', 'JNPR', 'JIH', 'ABMD', 'LLNW', 'HARP', 'STIM', 'RIDE', 'AME', 'ATRA', 'AGS', 'RNST', 'RADI', 'ALLY', 'TRVN', 'MHO', 'QCOM', 'KMX', 'PLMR', 
'AGFS', 'CTAC', 'CSOD', 'LSEA', 'RDFN', 'TIG', 'NYMX', 'FOUR', 'POOL', 'XBIT', 'MANU', 'JBHT', 'KODK', 'AMD', 'TBLT', 'NVRO', 'CIEN', 'SANM', 'CRHC', 
'GOEV', 'ITT', 'NXTC', 'TFX', 'MG', 'CARS', 'CHS', 'LLY', 'WDC', 'UFS', 'SA', 'FRBK', 'VSAT', 'EMAN', 'BHLB', 'RPAY', 'LULU', 'SBG', 'K', 'VCRA', 'WSBC', 
'BIOX', 'PME', 'CMBM', 'KRO', 'FTS', 'CNR', 'REFR', 'HLI', 'CATM', 'PLTR', 'MAAC', 'UAL', 'ORCC', 'TRUE', 'INSG', 'CI', 'XXII', 'UPS', 'BLUE', 'ADV', 
'TOPS', 'KEY', 'EXPR', 'RMO', 'ACM', 'TWST', 'IMAX', 'BOOT', 'AEO', 'UBX', 'CNCE', 'SKY', 'RESN', 'SSB', 'MCHX', 'ROL', 'UNM', 'HRC', 'SSPK', 'HP', 'RNR',
 'LII', 'GRBK', 'EYPT', 'ADNT', 'DKS', 'ACCD', 'MRC', 'CHNG', 'WH', 'CTXR', 'STCN', 'URG', 'RNG', 'DGNR', 'AVGO', 'ROKU', 'GLG', 'MGTA', 'FOCS', 'SLNO', 
'TCF', 'CHDN', 'HMN', 'GOSS', 'QRVO', 'FIZZ', 'VIAC', 'MLHR', 'ALE', 'FREE', 'HWC', 'FLXN', 'DRVN', 'NAVI', 'OSW', 'C', 'MFIN', 'VEEV', 'SBUX', 'RUN', 'HOLI',
 'EXTN', 'MWA', 'POAI', 'UONE', 'PXD', 'PINS', 'AZPN', 'ID', 'MRNA', 'SPNV', 'BBY', 'CVA', 'GRPN', 'TDC', 'PAYA', 'NGMS', 'ADXS', 
'SU', 'RBAC', 'LAD', 'SPT', 'RCUS', 'OPRT', 'ATR', 'DAL', 'SCPL', 'KIQ', 'HCKT', 'ALTU', 'KEN', 'BKR', 'NDAQ', 'MRCY', 'NR', 'J', 'ESGC', 'PZZA', 
'SWI', 'AFMD', 'GATX', 'STRL', 'MAXN', 'AMSC', 'TLRY', 'NLS', 'XPL', 'AVCO', 'INTU', 'PINC', 'SYRS', 'ZNTL', 'IHRT', 'LPX', 'CCK', 'MNRO', 'BNED', 'BLU', 
'SOAC', 'ASRT', 'BTWN', 'HFWA', 'VC', 'HCSG', 'ARCT', 'VGZ', 'AEM', 'KDP', 'BJ', 'GTN', 'SPR', 'SPLK', 'UMBF', 'CCJ', 'LKFN', 'VFC', 'SYKE', 'TGLS', 
'TR', 'MDU', 'GIL', 'CENTA', 'GE', 'LEA', 'HLF', 'AXSM', 'CMCSA', 'LASR', 'UBS', 'FL', 'CBAT', 'CHGG', 'CRTX', 'SPNE', 'FATE', 'HTBX', 'ATUS', 'TROW', 'DTIL',
 'AN', 'ATEC', 'ALKS', 'KTB', 'ADT', 'IBKR', 'VRCA', 'BMO', 'ADCT', 'ADMP', 'XNCR', 'STFC', 'SNPS', 'CNA', 'PENN', 'WLK', 'TREB', 'WCC', 'KSU', 'TUP', 'TFSL',
 'WERN', 'IOVA', 'GLDG', 'LCI', 'PRI', 'EYEN', 'III', 'MTSI', 'NMRK', 'SALM', 'NWSA', 'BTRS', 'ZEN', 'ALNY', 'CVI', 'XELA', 'SIX', 'PFC', 'REPL', 'VSTM', 
'HII', 'SCCO', 'RGNX', 'DRQ', 'KO', 'SWBI', 'IT', 'LCY', 'GLDD', 'NOVA', 'CO', 'SIBN', 'GNK', 'MATW', 'HZN', 'CRMD', 'SFNC', 'JAGX', 'RJF', 'FURY', 'ALGS',
 'SATS', 'ANSS', 'RRD', 'RICE', 'COTY', 'BIGC', 'ALK', 'IGMS', 'GOCO', 'VCYT', 'SUNW', 'KFY', 'VHC', 'GNUS', 'MOH', 'JCI', 'DSGX', 'SAIA', 'ATHX', 'SF', 
'SRGA', 'IRDM', 'DNN', 'ANET', 'SYBX', 'NGM', 'VOYA', 'TAST', 'DESP', 'KNSA', 'LPRO', 'PPL', 'ODFL', 'THTX', 'AGR', 'CRNT', 'GTE', 'LUNG', 'PRVB', 'NAKD', 
'CLF', 'CSLT', 'COHU', 'SC', 'VYGR', 'SPSC', 'TFII', 'ODT', 'CVS', 'VRSN', 'AMCX', 'SRNE', 'PIPP', 'STBA', 'NSTG', 'PAHC', 'AER', 'MRNS', 'LYFT', 'GTHX', 
'SIC', 'LUV', 'LBRDA', 'AM', 'PFGC', 'MMSI', 'WTRH', 'TRMK', 'CASA', 'PFIE', 'RIOT', 'ASIX', 'PLUG', 'AMRC', 'NEE', 'VERB', 'PLAB', 'STE', 'CKPT', 'BKNG', 
'TRV', 'BALY', 'ALLO', 'FTCV', 'CRNX', 'PRFT', 'ON', 'STN', 'LXFR', 'FOLD', 'MCRB', 'PPD', 'FAII', 'FBC', 'LANC', 'HZAC', 'SNPR', 'TG', 'PTVE', 'EXK', 'PVH', 
'ASGN', 'ORMP', 'ALEC', 'CMP', 'OMI', 'SEER', 'IRBT', 'MDB', 'GASS', 'PNW', 'FLR', 'PLYA', 'OBSV', 'AVRO', 'LRN', 'SCI', 'ADMS', 'ACAD', 'WW', 'NWS', 'EYE',
 'UBSI', 'PACW', 'GLOB', 'NYCB', 'IBIO', 'PODD', 'CAAP', 'PRAA', 'MLM', 'PGEN', 'SPOT', 'XERS', 'ANIX', 'TVTY', 'GSS', 'LOGI', 'EXPO', 'UTI', 'RBBN', 'AAU',
 'KNTE', 'MMI', 'JNCE', 'BBIO', 'HGBL', 'AR', 'RY', 'NNBR', 'AMTI', 'CTAQ', 'OMF', 'XL', 'TNET', 'SHAK', 'CL', 'CMLF', 'NLTX', 'EPIX', 'PRLD', 'ZUO', 'CERS',
 'CJJD', 'ESE', 'ORIC', 'ARES', 'SABR', 'DIS', 'AXGN', 'ADMA', 'MANH', 'CVLT', 'HTLF', 'CASY', 'ALDX', 'PRTK', 'ABEO', 'NRC', 'KLIC', 'CLVT', 'TD', 'ONTX', 
'BG', 'BEPC', 'BIIB', 'AAPL', 'XP', 'FNV', 'UVSP', 'WABC', 'STXS', 'DBD', 'GRWG', 'HIGA', 'RADA', 'GATO', 'PACK', 'UNP', 'OEC', 'LOCO', 'KEYS', 
'GNTX', 'BBI', 'TRU', 'DUK', 'ACIU', 'AQMS', 'VCVC', 'FAF', 'AKU', 'SPRQ', 'EMN', 'ACTC', 'PLIN', 'GD', 'FIBK', 'CPG', 'ENR', 'CNHI', 'BCSF', 'FTCH', 'GTES',
 'OTIC', 'VMW', 'SPB', 'ALSN', 'MX', 'ACEV', 'GNOG', 'SELB', 'PTCT', 'BE', 'BRKL', 'HYMC', 'FOX', 'GNCA', 'VERI', 'WLMS', 'COGT', 'UTZ', 'DARE', 'ZYME', 
'CLSK', 'BSY', 'GERN', 'BPMC', 'CVE', 'KOPN', 'FCF', 'ADBE', 'NOMD', 'MRTX', 'SNCR', 'MTW', 'CRDF', 'RNWK', 'CHKP', 'FSRV', 'TRQ', 'PUMP', 'HLT', 'APPN', 
'BLKB', 'BFAM', 'VVNT', 'PFSI', 'BWA', 'ORLY', 'ICL', 'QRTEA', 'RSG', 'SXT', 'FF', 'DEN', 'CP', 'ALV', 'ACRS', 'KPTI', 'CVBF', 'HA', 'TMHC', 'ETTX', 'PING',
 'IR', 'HOME', 'RRR', 'BR', 'PBYI', 'SAVE', 'TNXP', 'CDK', 'RFP', 'UNVR', 'QSR', 'ACCO', 'CHRW', 'TMDI', 'CARE', 'OESX', 'OCX', 'ARD', 'SOLO', 'CTSO', 'EPAM',
 'MDP', 'EXPI', 'MCK', 'KBAL', 'ATRS', 'DGLY', 'BLNK', 'MMC', 'GMS', 'CRNC', 'KW', 'FHTX', 'CVAC', 'HPK', 'LTHM', 'NVIV', 'FI', 'XRAY', 'GHLD', 'CALX', 'RTX',
 'SBGI', 'FTI', 'FUL', 'KURA', 'TPHS', 'QUOT', 'DOX', 'TH', 'FTEK', 'MELI', 'TUFN', 'PEP', 'DAN', 'PXS', 'PACE', 'APTO', 'PDCE', 'VMC', 'AIN', 'APTX', 'XPOA',
 'MRKR', 'DISH', 'DDD', 'MTDR', 'RYI', 'MHLD', 'SMAR', 'AMED', 'CNNE', 'CNXC', 'TANH', 'GS', 'BRY', 'CBZ', 'EBC', 'WIFI', 'CLBS', 'UWMC', 'RBA', 'AIHS', 'CVNA',
 'OLLI', 'AMN', 'CCNC', 'GLRE', 'CRSA', 'IACA', 'SYNH', 'RVLV', 'LB', 'IDXX', 'VINP', 'ACHC', 'ZIXI', 'STRM', 'EXN', 'RDUS', 'CRWD', 'HUGE', 'AMKR', 'APXT',
 'HBP', 'APG', 'MOD', 'HCHC', 'MCFE', 'GLTO', 'TLS', 'MCD', 'GEVO', 'SFIX', 'SON', 'TBIO', 'CDXS', 'AIG', 'FOXF', 'UVE', 'AAN', 'SEIC', 'LEN', 'SNX', 'CTS', 
'RETA', 'PNM', 'CLOV', 'LZB', 'ILMN', 'DRNA', 'RPD', 'FTNT', 'FVE', 'IRWD', 'UIS', 'CE', 'CMG', 'RDWR', 'HRTG', 'BHF', 'HPQ', 'ONCS', 'VTNR', 'MGLN', 'SMTS',
'BYD', 'CSII', 'LIND', 'MTCR', 'OSH', 'TEKK', 'TRI', 'NBIX', 'BLFS', 'THS', 'WRK', 'GOAC', 'SHW', 'SSNC', 'REPH', 'EURN', 'IAC', 'BW', 'WEN', 'MCS', 'SNBR', 
'BC', 'GDYN', 'DRRX', 'UAVS', 'LTRX', 'AUMN', 'DZSI', 'CDXC', 'WRAP', 'CHRA', 'DISCA', 'SSKN', 'FOXA', 'SB', 'ORA', 'PLSE', 'LPTH', 'BBCP', 'NRIX', 'RXT', 'HBT', 
'FICO', 'GDRX', 'TSLX', 'EXLS', 'EIG', 'HAAC', 'PLRX', 'FSV', 'PSTH', 'MSGN', 'CNMD', 'MRK', 'FITB', 'PBTS', 'CENX', 'BIG', 'LBAI', 'CLRB', 'HBNC', 'NMFC', 'LL',
 'ALNA', 'GBL', 'CNS', 'SLQT', 'BANF', 'LBRDK', 'FSM', 'RS', 'ALVR', 'ENZ', 'DENN', 'SNGX', 'FND', 'DCI', 'BV', 'EAF', 'RUSHA', 'BILL', 'IPG', 'DT', 'XOG', 'ULH',
 'SRCL', 'LXU', 'PHUN', 'BORR', 'DB', 'ARNC', 'CASI', 'MDLZ', 'CLSN', 'RMGB', 'KDNY', 'DEH', 'CMC', 'OPCH', 'PLXS', 'SWIR', 'SV', 'INPX', 'MRSN', 'TWOU',
 'QNST', 'DFS', 'KMB', 'CDW', 'ONCT', 'MPX', 'RGA', 'WST', 'HEES', 'FNKO', 'CIA', 'TW', 'ZG', 'ERF', 'ABNB', 'EVBG', 'TELL', 'WAB', 'FBIO', 'THO', 'PBA', 'EBF', 
'TEN', 'RVP', 'VCTR', 'MS', 'NVAX', 'DFNS', 'ZIOP', 'HTLD', 'TCPC', 'FANG', 'NEO', 'ASMB', 'NEXA', 'BGCP', 'HMPT', 'MFC', 'HOMB', 'PRAH', 'PSEC', 'BAC', 'TSEM', 
'AIZ', 'VTVT', 'SIGA', 'MDT', 'AVNS', 'CERN', 'SREV', 'WORK', 'AFG', 'INSW', 'CECE', 'WTTR', 'CND', 'HRL', 'FRTA', 'SUPN', 'ASC', 'KELYB', 'FHB', 'CIDM', 'ENSG', 
'SRE', 'MNTK', 'OI', 'ITOS', 'PBFS', 'LQDT', 'EOSE', 'OLN', 'CRY', 'SYF', 'AGTC', 'AFYA', 'HROW', 'HBAN', 'SEEL', 'BKH', 'CZR', 'MASS', 'ALXO', 'AQN', 'OPGN', 
'FLEX', 'PRDO', 'NPTN', 'NGVT', 'USB', 'OCA', 'BKI', 'EXEL', 'LILA', 'AFL', 'NBHC', 'NL', 'ACA', 'SPGI', 'DOOO', 'MCHP', 'ARLO', 'MIDD', 'FWRD', 'RE', 'EBIX', 
'FENC', 'QLYS', 'PIAI', 'HAE', 'INFO', 'CGBD', 'FLOW', 'EQX', 'UEC', 'DVA', 'SLCA', 'TRIP', 'PSTI', 'EAR', 'APA', 'SIVB', 'FB', 'XPER', 'VGR', 'AIRI', 'APAM',
 'VIR', 'GOOGL', 'YCBD', 'SGTX', 'CF', 'WWE', 'KAMN', 'ASAN', 'VRS', 'KGC', 'SURF', 'GME', 'AQUA', 'TVTX', 'XYL', 'WFG', 'EQH', 'XPEL', 'MLI', 'BAM', 'CUBI', 
'AUPH', 'MSM', 'PXLW', 'GSAT', 'WKHS',  'BRO', 'KMT', 'GPS', 'CCRN', 'AIT', 'SVMK', 'COMM', 'UFCS', 'HQY', 'AMGN', 'GSM', 'LFTR', 'CRS', 'BBBY', 'CRL',
 'NTRS', 'SWM', 'CTHR', 'HNI', 'ITI', 'JCOM', 'TNK', 'ATOS', 'CTSH', 'NCR', 'RIBT', 'KZR', 'SLRC', 'MAXR', 'PBF', 'ETH', 'CAMP', 'VIRT', 'MBI', 'VTGN', 
'FDMT', 'PAGS', 'CPRX', 'MTCH', 'IRTC', 'JAMF', 'WFC', 'AGCO', 'ZYXI', 'ABT', 'OPK', 'ORN', 'ERII', 'BEAM', 'AEL', 'TTI', 'SHOP', 'MEDP', 'INDB', 'MTOR', 'TRMB',
 'WMK', 'TDOC', 'HUBG', 'PRLB', 'UUUU', 'MCBC', 'OGS', 'PGTI', 'AG', 'CFX', 'GBDC', 'FLO', 'BAX', 'ICLR', 'BECN', 'TWLO', 'VRAY', 'NEXT', 'JLL', 'CWST', 'TTCF',
 'TRIT', 'ENB', 'TRST', 'RWLK', 'AMPH', 'DK', 'HBM', 'CYBR', 'NWN', 'DCRB', 'ZM', 'DG', 'FCAC', 'NTUS', 'NKLA', 'STKS', 'PASG', 'DBX', 'CIT', 'LMT', 'HFFG', 
'VAPO', 'CCIV', 'PPG', 'SKX', 'DGII', 'WNEB', 'MESA', 'BANR', 'VVV', 'STRO', 'DFH', 'BOWX', 'DHR', 'AXON', 'RYTM', 'RNA', 'ALLK', 'APPS', 'PLNT', 'ONDS', 'GSBD', 
'CADE', 'AVID', 'GGG', 'MEI', 'TREX', 'AL', 'ALRN', 'RYAM', 'ZUMZ', 'STAA', 'JWS', 'EQD', 'EXP', 'PAAS', 'CXDC', 'PETZ', 'IIIV', 'OTIS', 'SAIC', 'LSPD', 'ACEL',
 'CPA', 'LNC', 'LNTH', 'URI', 'SDGR', 'APPF', 'RAD', 'MMS', 'CEIX', 'EQT', 'HCC', 'EVTC', 'GSL', 'SCSC', 'WTRG', 'NUVA', 'LOW', 'OXY', 'TYME', 'HOL', 
'ECL', 'SIEN', 'BCE', 'LMND', 'NFE', 'EXPD', 'CXW', 'SLGN', 'SFT', 'HIL', 'BYFC', 'PNTG', 'PB', 'IFRX', 'TMUS', 'WEC', 'NOV', 'HSY', 'KBR', 'TRX', 'PHAT', 'HNRG',
 'LIVX', 'DCT', 'EAT', 'COLM', 'CPB', 'WNC', 'TGA', 'METX', 'AVGR', 'NMIH', 'ENS', 'VERX', 'EEX', 'DCPH', 'TARO', 'LUNA', 'CRON', 'MGEE', 'AGC', 'EWBC', 'KMPH', 
'TBBK', 'MTH', 'CROX', 'WK', 'AESE', 'TMBR', 'CSGS', 'BDX', 'FRME', 'CNST', 'EIX', 'CCCC', 'DLTH', 'TDS', 'DDOG', 'EGHT', 'MMYT', 'NVCN', 'EHC', 'NOAC',
 'OMCL', 'ORGO', 'ZGNX', 'POR', 'AMSWA', 'CNTY', 'CRM', 'CRUS', 'TTEK', 'SAH', 'OZK', 'HTBK', 'PCG', 'WAL', 'PCTY', 'SUP', 'OMC', 'DVAX', 'DBI', 'IPOF', 'DOMO',
 'CLDX', 'GDEN', 'SILK', 'AOS', 'ENG', 'AERI', 'MAR', 'NWL', 'CHMA', 'GIS', 'PSNL', 'R', 'CRBP', 'HFC', 'ATGE', 'SAGE', 'CSIQ', 'LQDA', 'AMG', 'SIG', 'CTXS',
 'TIPT', 'STAF', 'TAP', 'KEX', 'LIN', 'CERC', 'ABCB', 'NFBK', 'BX', 'CG', 'BKE', 'HCAT', 'FIVE', 'NYT', 'RTP', 'GLYC', 'EW', 'LXRX', 'VBTX', 'MSCI', 'BDTX', 
'NMTR', 'ARRY', 'AGRO', 'PRO', 'HZON', 'FFIV', 'COP', 'UTHR', 'CHEF', 'BOAC', 'KRA', 'BAH', 'PANW', 'ACGL', 'LYTS', 'MSA', 'NCLH', 'CARR', 'V', 'OXSQ', 'MCO', 
'FLS', 'MVIS', 'SLB', 'ADTN', 'AGIO', 'AXTI', 'OMER', 'ZNGA', 'ONB', 'SPPI', 'ELA', 'SHIP', 'CLR', 'JEF', 'NTP', 'CBU', 'DHI', 'ACST', 'AIKI', 'LJPC', 'MIC', 
'STLD', 'QUAD', 'W', 'EVOP', 'LE', 'G', 'ZBH', 'FLT', 'AIR', 'EMPW', 'VLO', 'GOLD', 'VHI', 'OPTT', 'KL', 'EFX', 'LESL', 'SSP', 'HHC', 'HBIO', 'NOA', 'STNE', 
'BWMX', 'RHI', 'AYRO', 'ITRG', 'AYX', 'AAOI', 'EFSC', 'MGA', 'BLX', 'VSH', 'LUMN', 'RIGL', 'FROG', 'OSG', 'MEIP', 'FBK', 'IDA', 'EVRG', 'IDRA', 'NINE', 'USX', 
'ED', 'CNXN', 'CMPR', 'ICHR', 'WISH', 'NARI', 'HXL', 'PHAS', 'AXS', 'TECK', 'AVYA', 'MTB', 'ALUS', 'STEP', 'SCHL', 'STIC', 'OCFC', 'BYND', 'VNOM', 'OCDX', 
'SVM', 'PSTX', 'TRIN', 'EBON', 'ADS', 'CURI', 'CWH', 'ATRC', 'NEBC', 'TXN', 'BGS', 'MU', 'MDWD', 'YTRA', 'FNB', 'WRB', 'BLMN', 'BOMN', 'EPAY', 'FSKR', 'INSP', 
'VERO', 'TGH', 'FREQ', 'SPKE', 'WLTW', 'LKCO', 'BL', 'ALTG', 'FCN', 'BSGM', 'GLT', 'OPEN', 'MARK', 'SAIL', 'PEN', 'INUV', 'ADM', 'BHE', 'WLL', 'ABC', 'TWND', 
'ONCY', 'HZNP', 'IZEA', 'PLAY', 'PETQ', 'LHCG', 'MTX', 'WAFD', 'ECHO', 'AXL', 'KRNY', 'CLSD', 'FLMN', 'HAPP', 'WOW', 'TLMD', 'DSX', 'ARDX', 'OVV', 'DOW', 'GIII',
 'AMTX', 'GH', 'APSG', 'PRQR', 'AWK', 'PRGO', 'UCTT', 'FDS', 'CLH', 'OSK', 'IVZ', 'VIVO', 'TXG', 'NSIT', 'SWK', 'VNRX', 'KTRA', 'NCNO', 'MSFT', 'WGO', 'AAON', 
'KTOS', 'KMPR', 'IPOD', 'CCX', 'CDMO', 'VZ', 'EBS', 'CAP', 'DGX', 'AMBA', 'MTN', 'CASH', 'SENS', 'ARCB', 'UTSI', 'WMT', 'BLDP', 'MERC', 'MRUS', 'MPC', 
'DOCU', 'ST', 'IMXI', 'JOE', 'SEE', 'SLDB', 'HAFC', 'BHC', 'CFFN', 'ENVA', 'AMAT', 'NXPI', 'SCS', 'ACND', 'WHD', 'DFIN', 'PSX', 'TRCH', 'BBDC', 'DY', 'GPK', 
'PGNY', 'KAR', 'UIHC', 'ASPN', 'AUDC', 'SKYW', 'INMD', 'TSLA', 'SYNA', 'CTVA', 'LEAP', 'LKQ', 'JBL', 'SHOO', 'CSX', 'CFRX', 'X', 'BURL', 'OGE', 
'MGY', 'TKR', 'TISI', 'MDXG', 'CMA', 'ATI', 'GPN', 'CERE', 'MKC', 'HALO', 'QLI', 'APO', 'TCS', 'LEVI', 'TPR', 'TBI', 'GRC', 'TGP', 'CRK', 'WEX', 'SM', 'TRMD', 
'RGS', 'AONE', 'AKTS', 'CLDR', 'FLGT', 'SMSI', 'MRTN', 'PCAR', 'RBC', 'ALT', 'SJR', 'PEGA', 'REGI', 'ARQT', 'GNE', 'TRIL', 'ETR', 'SHEN', 'AGRX', 'BIO', 'ODP', 
'ALGM', 'SMCI', 'NKE', 'CLS', 'IIVI', 'WSO', 'WBS', 'FRG', 'EA', 'AES', 'SUMO', 'SIGI', 'HGEN', 'CLAR', 'REED', 'LBTYA', 'DCOM', 'NESR', 'ADI', 'TU', 'MO', 'HWM',
 'TECH', 'ZIM', 'SJW', 'FIS', 'KBH', 'SCOR', 'CHD', 'OR', 'GOOS', 'SFL', 'ATNX', 'HESM', 'TOL', 'AAP', 'EXFO', 'CAR', 'SPCE', 'COST', 'AGCB', 'GILT', 'PRA', 
'FDX', 'PACB', 'BCOR', 'ANNX', 'ICPT', 'CDNA', 'LYV', 'YEXT', 'VYGG', 'LOTZ', 'LUB', 'AMK', 'BATL', 'AWH', 'TMST', 'JNJ', 'TPGY', 'KDMN', 'BPFH', 'FOR', 'ETAC',
 'KSMT', 'FE', 'JBT', 'CNDT', 'ADSK', 'FSR', 'AREC', 'LOB', 'CVGI', 'MAN', 'FPAC', 'FHI', 'NWE', 'SGMO', 'RMR', 'EGAN', 'HYFM', 'XPO', 'BRKR', 'TUSK', 'NXGN', 
'VNE', 'AGMH', 'DTE', 'SPRO', 'STSA', 'QELL', 'ALLE', 'UHS', 'HLNE', 'GCMG', 'AXDX', 'CHRS', 'SASR', 'BCAB', 'AHCO', 'NVT', 'GOOG', 'IGC', 'JELD', 'GRSV', 
'QRTEB', 'AXTA', 'BCC', 'ROCK', 'APOG', 'ESTE', 'CTMX', 'CYH', 'KELYA', 'ALB', 'GBX', 'SNDX', 'DLTR', 'MCY', 'SYK', 'POSH', 'CMD', 'WPF', 'WTS', 'FULC', 'NOVN', 
'ELF', 'SWN', 'TRS', 'OIS', 'MGTX', 'LGVN', 'MIST', 'VFF', 'CERT', 'NVDA', 'VREX', 'MOGO', 'DE', 'VCEL', 'BOXL', 'FCRD', 'LDOS', 'REKR', 'THBR', 'TRGP', 'AKUS',
 'LPSN', 'HLIO', 'ENV', 'THM', 'CSPR', 'CDE', 'PKG', 'MEG', 'ORCL', 'EQOS', 'ASLE', 'FULT', 'ONTO', 'AEE', 'CDEV', 'ALTO', 'LH', 'CBRE', 'APM', 'BAP', 
'SILV', 'COLB', 'BCOV', 'QTRX', 'ADP', 'VRTX', 'LHX', 'WRN', 'POWW', 'RARE', 'APYX', 'XRX', 'FCFS', 'CRSR', 'SOI', 'VIACA', 'ZBRA', 'SPXC', 'GDOT', 'TPH', 
'STX', 'ITGR', 'MITK', 'TJX', 'SNOW', 'CAH', 'HIG', 'PROG', 'ZS', 'WVE', 'FUBO', 'GNLN', 'TAC', 'NTB', 'CCAC', 'SRT', 'ABUS', 'KALA', 'VBIV', 'COWN', 'ROAD', 
'SMPL', 'ELVT', 'KOD', 'CSL', 'GES', 'FORM', 'RCM', 'XTNT', 'BTG', 'LNT', 'IFF', 'ARMK', 'CONN', 'BCEL', 'AX', 'SCVX', 'MTRX', 'PRPB', 'MOTS', 'RAVN', 'FSLY', 
'IMO', 'MYOV', 'DNOW', 'RACE', 'MKTX', 'IDCC', 'TNDM', 'MAIN', 'UNH', 'IONS', 'SGEN', 'SPFR', 'PG', 'PLTK', 'NVST', 'SRAC', 'RMTI', 'VYNE', 'ALXN', 'PYPL', 
'LPLA', 'HOLX', 'REV', 'FIVN', 'MHK', 'AKAM', 'SCPH', 'TWNK', 'LW', 'UI', 'MPLN', 'NOC', 'IBP', 'TMX', 'RF', 'KRTX', 'GT', 'CAT', 'WTER', 'SUM', 'GSKY', 'VTOL', 
'VMD', 'BSIG', 'KLDO', 'HRB', 'TSC', 'CDZI', 'MDVL', 'ROST', 'DRTT', 'SR', 'CLIR', 'OVID', 'DNLI', 'LBC', 'HBI', 'OSUR', 'DMTK', 'PRU', 'GTBP', 'AIM', 'SBLK', 
'ACLS', 'ACIC', 'IAA', 'DOV', 'LECO', 'XENT', 'MIRM', 'EXC', 'ITRI', 'NAT', 'STKL', 'DFFN', 'MC', 'MDLA', 'PDCO', 'VITL', 'INO', 'PCRX', 'BEN', 'BK', 'NXTD', 
'WBA', 'DS', 'ELY', 'RMBS', 'BUR', 'ICE', 'SPNS', 'CNO', 'OM', 'FFBC', 'RCII', 'IMGN', 'TPTX', 'CENT', 'PTE', 'ASB', 'MDRX', 'NAV', 'CFAC', 'STWO', 'TEAM', 
'ALSK', 'Z', 'ENOB', 'FSLR', 'EME', 'HPE', 'SHYF', 'CNSL', 'DSSI', 'SO', 'ACI', 'BXRX', 'AVD', 'PRTY', 'ARVN', 'AXP', 'LOKB', 'CGEN', 'ENDP', 'VNT', 'GNPX', 
'GRUB', 'MDNA', 'RRC', 'KRMD', 'MUX', 'RCKT', 'WSM', 'OPTN', 'NTNX', 'EL', 'TSE', 'GWB', 'UPLD', 'GNRS', 'CBT', 'LTRPA', 'NWBI', 'ALLT', 'NTR', 'TRC',
 'UNFI', 'CARG', 'CCEP', 'APLS', 'CYRX', 'HON', 'DCBO', 'PANL', 'APTV', 'BRBR', 'PUBM', 'DKNG', 'BCRX', 'PEG', 'PFE', 'FRPT', 'DYAI', 'MARA', 'SJ', 'NUAN', 
'ITRM', 'VRNS', 'GTLS', 'PSMT', 'WTI', 'CMRE', 'BA', 'INGR', 'CWK', 'CVM', 'RDNT', 'TT', 'SQ', 'OACB', 'DLX', 'OCUL', 'DD',  'ORBC', 'REZI', 'MGI', 'ASH', 
'NKTX', 'USIO', 'AAL', 'FBHS', 'EDIT', 'OLED', 'FTV', 'FTFT', 'MKSI', 'COCP', 'SBH', 'AMTB', 'FUSN', 'ENPH', 'AVXL', 'PZN', 'ONCR', 'VICR', 'SJM', 'RVNC', 
'RGLD', 'PNC', 'ABCL', 'CURO', 'SBSI', 'MGNI', 'NERV', 'PNNT', 'FLNG', 'SSTK', 'F', 'ELAN', 'OKTA', 'WU', 'PAYX', 'RES', 'AMP', 'FGEN', 'AMBC', 'PPC', 'VIH', 
'SGOC', 'SCOA', 'CGC', 'RAMP', 'ERIE', 'FCX', 'MRVL', 'NBEV', 'INSM', 'LILAK', 'CFR', 'BLL', 'VNTR', 'CBAY', 'MBII', 'NCMI', 'MGIC', 'BUSE', 'MPWR', 'HUBS', 
'GKOS', 'BDSI', 'B', 'BKU', 'NEM', 'PDFS', 'CIGI', 'FNF', 'ATCO', 'WPRT', 'HOG', 'TSIA', 'XOM', 'GCI', 'MBIO', 'TPX', 'TPC', 'MSP', 'ESTC', 'MCBS', 
'SHLS', 'TRN', 'MXL', 'EBSB', 'HMLP', 'AMRX', 'CMI', 'COF', 'NTGR', 'WSFS', 'STNG', 'SNAP', 'AGEN', 'OII', 'AKRO', 'SFBS', 'CARA', 'AVEO', 'BROG', 'NLOK', 
'FCEL', 'FRO', 'VCNX', 'REYN', 'PRTA', 'VECO', 'LINC', 'CPF', 'OTTR', 'KLAC', 'CWBR', 'CBIO', 'IDT', 'CFB', 'DHT', 'DNMR', 'AMWL', 'BRKS', 'KOS', 'CDTX', 'SWCH', 
 'HEI', 'ESPR', 'TPIC', 'AINV', 'USAS', 'MTG', 'KYMR', 'IEX', 'DNB', 'AUB', 'RUSHB', 'OCGN', 'RMD', 'SLM', 'CHH', 'GLAD', 'THRM', 'RPTX', 'INFN', 'KN', 
'SIRI', 'MTC', 'NSP', 'AVIR', 'ZI', 'BNS', 'AFRM', 'SBCF', 'YMAB', 'SND', 'PAYS', 'PHM', 'AGI', 'WAT', 'SQZ', 'GLOG', 'GWRE', 'TCDA', 'WOOF', 'CPE', 'ISR', 
'NGAC', 'SAVA', 'DGICA', 'EVH', 'SEM', 'AKBA', 'BKD', 'TMO', 'HUM', 'HSC', 'KRNT', 'FLDM', 'MUSA', 'KOR', 'CLX', 'FFIN', 'AJG', 'AQB', 'HAS', 'MYGN', 'VRRM', 
'KRON', 'JHG', 'DASH', 'HDSN', 'SONO', 'ISBC', 'CIXX', 'AACQ', 'LUXA', 'UBER', 'PTEN', 'CPRT', 'HAL', 'IP', 'KMI', 'WBT', 'VTRS', 'COG', 'REAL', 'DHX', 
'ADVM', 'PDAC', 'EZPW', 'CDNS', 'VBLT', 'USFD', 'TXT', 'QMCO', 'LC', 'SBT', 'BTBT', 'PWFL', 'BLBD', 'ETN', 'ASO', 'CPRI', 'KNDI', 'XLNX', 'FAST', 'IQV', 
'BOX', 'KNX', 'YNDX', 'OC', 'EPC', 'NBTB', 'HTGC', 'MATX', 'QTWO', 'GBT', 'HOFV', 'CALA', 'HE', 'AXU', 'WATT', 'VRT', 'SAII', 'NJR', 'PRCH',  'CCOI', 
'SWKS', 'OCSL', 'BTU', 'CAKE', 'FVRR', 'FTDR', 'BWB', 'WYNN', 'GRNQ', 'ISEE', 'CHNR', 'CW', 'PFMT', 'ERES', 'EXPE', 'BSX', 'ABM', 'TDG', 'IPGP', 'BTAQ', 
'AMCR', 'NEX', 'CWEN', 'ESLT', 'HTH', 'OKE', 'CR', 'SBTX', 'FTK', 'NFG', 'HMTV', 'THR', 'OSTK', 'TILE', 'OEG', 'U', 'IBTX', 'INOD', 'EXAS', 'ALC', 'WTFC', 
'NUE', 'SKLZ', 'CCO', 'ARW', 'PMVP', 'WIX', 'WINT', 'SITE', 'NVGS', 'SSYS', 'FIII', 'GOGL', 'BNFT', 'GTYH', 'QURE', 'BMY', 'VGAC', 'SEAH', 'POWI', 'ATHA', 
'SPWH', 'CSCO', 'PAGP', 'PSAC', 'TALO', 'RSI', 'CHEK', 'EVC', 'TTMI', 'PFG', 'EPAC', 'LBTYK', 'TINV', 'JBLU', 'DAR', 'INCY', 'DSS', 'ATH', 'CLNN', 'ATRO', 
'LPTX', 'MXIM', 'NTRA', 'ZOM', 'MNOV', 'ARC', 'ORI', 'MGM', 'AA', 'BBGI', 'RCHG', 'SPTN', 'NKTR', 'BHVN', 'PM', 'TLGT', 'SWX', 'SONM', 'PKI', 'TER', 'GDDY', 
'SIEB', 'CME', 'IMV', 'FLL', 'WING', 'IDYA', 'TWTR', 'BRQS', 'DSKE', 'QLGN', 'ROOT', 'COLL', 'SRPT', 'NX', 'EQ', 'RPM', 'FELE', 'KKR', 'GWW', 'ZSAN', 
'SGU', 'ACTG', 'ES', 'T', 'CCAP', 'RLAY',  'CORE', 'NUS', 'BOH', 'TTD', 'UGI', 'SNV', 'EPZM', 'GORO', 'EHTH', 'OYST', 'PAX', 'NOVT', 'MET', 'FRHC', 'GFF', 
'TGNA', 'UONEK', 'IGAC', 'OBLG', 'PBH', 'OSMT', 'CREE', 'QDEL', 'RIG', 'TGTX', 'CYCN', 'AGLE', 'INBX', 'EPM', 'CRIS', 'CMRX', 'ANTM', 'CTLT', 'SMTC', 'TWI', 
'HRTX', 'SCWX', 'SESN', 'SMG', 'GCP', 'GM', 'ARWR', 'FDP', 'ATO', 'TRUP', 'EVLO', 'AQST', 'ARPO', 'DTEA', 'LCAP', 'COMS', 'TK', 'ULTA', 'KIN', 'QTNT', 'LCII',
 'MIME', 'HLX', 'DMS', 'FSK', 'INT', 'ATCX', 'MASI', 'SANW', 'HI', 'PSTG', 'GLOP', 'NOW', 'DISCB', 'LAZ', 'CALM', 'LMNX', 'ANDE', 'OSBC', 'GILD', 'TCBI', 'ANGO',
 'AZEK', 'BDSX', 'NVMI', 'TSCO', 'SCHN', 'SRRK', 'CB', 'PERI', 'VET', 'PWR', 'CCL', 'CNC', 'NBRV', 'USWS', 'FIX', 'XCUR', 'FMC', 'VRSK', 'IMPX', 'UCBI', 'GAU',
 'EVER', 'AVLR', 'DPZ', 'PPBI', 'HSTM', 'BYSI', 'TTC', 'AEIS', 'HL', 'LOOP', 'THG', 'AWI', 'TTEC', 'ALJJ', 'GO', 'SSD', 'DOGZ', 'PROS', 'ROLL', 'HEXO', 'GRA', 
'PTON', 'GNSS', 'CRVS', 'CSGP', 'RSSS', 'LSTR', 'TXMD', 'PII', 'ZTS',  'LAZR', 'EGBN', 'MANT', 'BLD', 'LMNL', 'MMM', 'BPOP', 'CC', 'ASM', 'CBSH', 'TACO',
 'MNRL', 'CLGX', 'COUP', 'VG', 'GVA', 'CAAS', 'TDW', 'ACRX', 'KSS', 'PSN', 'WMG', 'MNKD', 'FN', 'PRMW', 'THCB', 'BNGO', 'CONX', 'APLT', 'CDLX', 'CLVS', 'BANC', 
'JWN', 'AEP', 'FIXX', 'AXNX', 'ZION', 'IGT', 'TSHA', 'PGR', 'MODN', 'CRSP', 'CSCW', 'CMTL', 'TOWN', 'CAMT', 'IART', 'CLB', 'WMB', 'FSS', 'XM', 'NTLA', 'WCN', 
'OFG', 'ENTG', 'WWD', 'LITE', 'RCI', 'EEFT', 'ANAT', 'WDAY', 'TROX', 'GSHD', 'ABST', 'ZYNE', 'CLII', 'AEZS', 'PULM', 'UPWK', 'NLSN', 'GLW', 'L', 'HES', 'HUN', 
'XEL', 'EVRI', 'HSTO', 'ATIF', 'CAL', 'HMHC', 'PFS', 'FMTX', 'CVET', 'DM', 'CBB', 'RGLS', 'PRGS', 'RSVA', 'TCBK', 'BCO', 'NEOG', 'NEWR', 'BRP', 'AMAL', 'SWAV', 
'MSI', 'ECOM', 'PTGX', 'CSTM', 'TGT',  'GSMG', 'EIGR', 'EVFM', 'ARCO', 'ROK', 'TPVG', 'JKHY', 'AGO', 'DAKT', 'MRO', 'NFH', 'BB', 'GIB', 'SNDL', 'DECK', 
'STLA', 'PAG', 'LPCN', 'RUTH', 'RGEN', 'LVS', 'AXLA', 'FRGI', 'ECOR', 'GTT', 'RCL', 'ACB', 'THRY', 'AON', 'FUSE', 'ARKO', 'AIMC', 'AMPY', 'INFI', 'SNDR', 'PTMN',
 'CM', 'GOGO', 'DELL', 'FTOC', 'DXCM', 'ALTR', 'CVX', 'HAIN', 'GOLF', 'OTEX', 'CRC', 'SRCE', 'HOOK', 'TRP', 'RUBY', 'PRTS', 'STC', 'AVO', 'ATKR', 'SRI', 'IFMK', 
'TTOO', 'CLBK', 'USM', 'AOSL', 'EB', 'IAG', 'UEPS', 'ACIW', 'XSPA', 'TEX', 'LORL', 'TIGO', 'GPRO', 'CINF', 'ATEN', 'SMMT', 'SFTW', 'BIOL', 'BXS', 'DIOD', 'NTAP', 
'TBPH', 'ASTC', 'SAND', 'SII', 'RTPZ', 'MICT', 'AJRD', 'ANF', 'TMQ', 'CNOB', 'HUBB', 'CRI', 'AI', 'HIMS', 'MOTV', 'CHWY', 'GNW', 'GPL', 'ISRG', 'CAE', 'ASPL', 
'NRG', 'HLIT', 'RL', 'FMBI', 'FHN', 'ARNA', 'PNR', 'PFLT', 'SEDG', 'DORM', 'FOE', 'INOV', 'SEAC', 'HSIC', 'ITW', 'LRCX', 'TCRR', 'FLNT', 'AFIB', 'POST', 'HGV', 
'CCMP', 'ECOL', 'MAT', 'GFL', 'TMDX', 'PHR', 'CFMS', 'DYN', 'AVAN', 'HCA', 'UPST', 'NI', 'NHIC', 'OSPN', 'IMVT', 'BY', 'MNST', 'ETSY', 'ESNT', 'QS', 'SCU', 'AAWW', 
'FEYE', 'WHR', 'GAIN', 'EVOK', 'DVN', 'MD', 'SFM', 'WSBF', 'ARAY', 'EMX', 'BIPC', 'NDLS', 'ROP', 'LPG', 'LSCC', 'CORT', 'BWXT', 'SIOX', 'MBRX', 'CTAS', 'BCPC', 
'TXRH', 'WETF', 'EOG', 'AVTR', 'LNDC', 'FMAC', 'ACN', 'WD', 'DPW', 'PLAN', 'QGEN', 'HONE', 'VLDR', 'ACAC', 'XENE', 'SGRY', 'CGEM', 'MUR', 'NFLX', 'GPC', 'MDCA', 
'PNFP', 'NDSN', 'PRAX', 'GWGH', 'A', 'UMPQ', 'EMR', 'XLRN', 'YELP', 'AZZ', 'STON', 'VRM', 'EMKR', 'LAUR', 'STTK', 'CHX', 'OGI', 'PVG', 'TEL', 'AMPE', 'WWR', 'PD', 
'LBRT', 'ESI', 'AMEH', 'CSTE', 'KHC', 'RPRX', 'BERY', 'FGNA', 'CNP', 'GPRE', 'UAA', 'CHTR', 'CUE', 'PCVX', 'OLMA', 'WOR', 'FRC', 'APH', 'M', 'CNI', 'FOSL', 'TGI',
 'GAN', 'INTC', 'EVR', 'PRTH', 'CACI', 'WM', 'ARGO', 'BZH', 'FBP', 'LOPE', 'VACQ', 'MORN', 'ONEM', 'REGN', 'FMNB', 'GSV', 'TTGT', 'RLI', 'VSTA', 'SLF', 'NTCT', 'HD',
 'DRI', 'SYN', 'METC', 'OTLK', 'FAMI', 'VOR', 'EBAY', 'GPRK', 'KNL', 'VAC', 'HOPE', 'PARR', 'BKCC', 'KMDA', 'STOK', 'EGO', 'ACET', 'VXRT', 'TENB', 'BMI', 'WWW', 
'VISL', 'VSTO', 'SWTX', 'ALRM', 'FUV', 'SDPI', 'ARCE', 'GMED', 'ETRN', 'RILY', 'TYL', 'AYI', 'CNQ', 'IVC', 'YUMC', 'COO', 'MBIN', 'VLY', 'CNSP', 'AZRX', 'HYLN', 
'CGNX', 'HNGR', 'NVCR', 'TGB', 'SGMS', 'WMS', 'ARCC', 'MAS', 'CDAY', 'NNI', 'BLDR', 'PBPB', 'PFPT', 'APEN', 'TDY', 'GMDA', 'GEG', 'SDC', 'CPHI', 'CMS', 'MORF', 
'DLB', 'ANAB', 'CTIC', 'ITCI', 'TWCT', 'LFMD', 'STT', 'AVA', 'LEAF', 'ECPG', 'LEG', 'LYB', 'SBNY', 'VRA', 'JAZZ', 'FPH', 'WSC', 'GABC', 'TSN', 'STL', 'NSC', 'GALT', 
'UA', 'GNRC', 'PRG', 'CYD', 'TRTN', 'LAC', 'CATY', 'CTB', 'NNOX', 'MTEM', 'CCS', 'VERU', 'RXN', 'UFPI', 'CAG', 'THC', 'APD', 'HRMY', 'JRVR', 'SNA', 'INVA', 'IMTX'
]
